services:
  arsenalot:
    build: .
    container_name: arsenalot-app
    # network_mode: host es necesario para que nmap y tshark vean las interfaces reales
    network_mode: host
    privileged: true
    volumes:
      - ./results:/app/results
    environment:
      - NEO4J_HOST=localhost
      - NEO4J_PORT=7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=neo4j123
    restart: unless-stopped
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:ubi9
    container_name: arsenalot-neo4j
    ports:
      - "7474:7474" # Browser UI
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
