version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: arsenalot_neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=none
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./results/neo4j_data:/data
      - ./results/neo4j_logs:/logs
    restart: unless-stopped

  neodash:
    image: neo4jlabs/neodash:latest
    container_name: arsenalot_neodash
    ports:
      - "5005:5005" # Default NeoDash port
    volumes:
      # Montamos el dashboard.json local en la ruta por defecto que lee NeoDash internamente
      - ./dashboard.json:/usr/share/nginx/html/dashboard.json:ro
    environment:
      - ssoEnabled=false
    depends_on:
      - neo4j
    restart: unless-stopped
